# Generated by Django 5.0 on 2024-01-09 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_user_token"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
